// SvelteMovies/src/Form.svelte
<script>
    const movies = [
    {
        name: "Avengers",
        quantity: 0,
        available: 3
    },
    {
        name: "Terminator",
        quantity: 0,
        available: 5
    }
    ];
</script>

{#each movies as movie}
<form>
    <h3>
        {movie.name}
    </h3>

    <button type="button" on:click={ () => movie.quantity -= 1} disabled={movie.quantity ===0}>
        -
    </button>
    {movie.quantity}
    <button type="button" on:click={ () => movie.quantity += 1} disabled={movie.quantity >= movie.available}>
        +
    </button>
</form>
{/each}

// React/src/Form.jsx
import React from "react";

export default function Form(props) {
const [quantity, setQuantity] = React.useState(0);
const { movie } = props;

return (
    <form>
    <h3>{movie.name}</h3>
    <button
        type="button"
        onClick={() => setQuantity(quantity - 1)}
        disabled={quantity === 0}
    >
        -
    </button>
    {quantity}
    <button
        type="button"
        onClick={() => setQuantity(quantity + 1)}
        disabled={quantity >= movie.available}
    >
        +
    </button>
    </form>
);
}
